site_name: Pi Web
docs_dir: docs

site_url: https://andrewhowdencom.github.io/pi/web/
repo_url: https://github.com/andrewhowdencom/pi.web
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/andrewhowdencom/pi.web
  generator: false

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
